/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package antraslaboratorinis;

import DuomenuStrukturos.AsmeniniuFinansuValdymas;
import DuomenuStrukturos.Kategorija;
import DuomenuStrukturos.PiniguJudejimas;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;

/**
 *
 * @author Berniszu
 */
public class GUI extends javax.swing.JFrame {

    AsmeniniuFinansuValdymas afv = new AsmeniniuFinansuValdymas();
    KategorijuSarasas katSar = new KategorijuSarasas(afv);

    public GUI() {
        initComponents();
        atnaujintiSarasa();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        l_data1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        l_data2 = new javax.swing.JTextField();
        m_filtruoti = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        KategorijosKurimas = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        grafikas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Asmeniniu finansu valdymo sistema");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nr", "Kategorija", "Pavadinimas", "Data", "Suma", "Tipas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        l_data1.setText("2019-03-01");
        l_data1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_data1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Data nuo: ");

        jLabel2.setText("Data iki: ");

        l_data2.setText("2019-04-01");
        l_data2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_data2ActionPerformed(evt);
            }
        });

        m_filtruoti.setText("Filtruoti");
        m_filtruoti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_filtruotiActionPerformed(evt);
            }
        });

        jButton1.setText("Istrinti pinigu judejima");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("Failas");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Atverti finansu faila");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Prideti nauja finansu valdyma");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Saugoti duomenis faile");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Baigti darba");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Kategorijos");

        KategorijosKurimas.setText("Kurti nauja kategorija");
        KategorijosKurimas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KategorijosKurimasActionPerformed(evt);
            }
        });
        jMenu2.add(KategorijosKurimas);

        jMenuItem5.setText("Perziureti kategoriju sarasa");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Finansai");

        jMenuItem7.setText("Prideti islaidas");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Prideti pajamas");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Apie");

        jMenuItem9.setText("Apie programa");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Grafikas");

        grafikas.setText("Balanso Grafikas");
        grafikas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grafikasActionPerformed(evt);
            }
        });
        jMenu5.add(grafikas);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(l_data1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(l_data2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(m_filtruoti, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(l_data1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(l_data2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_filtruoti)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        katSar.atnaujintiKategorijuLentele();
        katSar.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        //islaidos
        if (afv.gautikategorijuSarasa().size() > 0) {
            IslaiduIvedimas isv = new IslaiduIvedimas(this, true, afv);
            isv.setVisible(true);
            atnaujintiSarasa();
        } else {
            JOptionPane.showMessageDialog(this, "Pirma pridekite bent viena kategorija");
        }
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        //Apie programa
        ApiePrograma apie = new ApiePrograma(this, true);
        apie.setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void l_data1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_data1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_data1ActionPerformed

    private void l_data2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_data2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_data2ActionPerformed

    private void m_filtruotiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_filtruotiActionPerformed
        //filtravimo mygtukas
        filtruotiSarasa();
    }//GEN-LAST:event_m_filtruotiActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        afv = new AsmeniniuFinansuValdymas();
        afv.pridetiKategorija("Kat pav", "Aprasymas");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        JFileChooser langas = new JFileChooser();
        langas.setFileFilter(new FileNameExtensionFilter("AVF failas", "avf"));
        int rez = langas.showOpenDialog(null);
        if (rez == JFileChooser.APPROVE_OPTION) {
            File failas = langas.getSelectedFile();
            try {
                ObjectInputStream out = new ObjectInputStream(new FileInputStream(failas));
                afv = (AsmeniniuFinansuValdymas) out.readObject();
                out.close();
                atnaujintiSarasa();
            } catch (Exception e) {
                System.out.println("Nenuskaityti duomenys");
                JOptionPane.showMessageDialog(this, "klaida nuskaitant faila", "Klaida", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JFileChooser langas = new JFileChooser();
        langas.setFileFilter(new FileNameExtensionFilter("AVF failas", "avf"));
        int rez = langas.showSaveDialog(this);
        if (rez == JFileChooser.APPROVE_OPTION) {
            try {
                ObjectOutputStream out = new ObjectOutputStream(new FileOutputStream(langas.getSelectedFile()));
                out.writeObject(afv);
                out.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "klaida nuskaitant faila", "Klaida", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void KategorijosKurimasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KategorijosKurimasActionPerformed
        KategorijosIvedimas kiv = new KategorijosIvedimas(this, true, afv);
        kiv.setVisible(true);
        katSar.atnaujintiKategorijuLentele();
        katSar.repaint();
    }//GEN-LAST:event_KategorijosKurimasActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // Pajamos
        if (afv.gautikategorijuSarasa().size() > 0) {
            PajamuIvedimas isv = new PajamuIvedimas(this, true, afv);
            isv.setVisible(true);
            atnaujintiSarasa();
        } else {
            JOptionPane.showMessageDialog(this, "Pirma pridekite bent viena kategorija");
        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void grafikasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grafikasActionPerformed
        Grafikai ex = new Grafikai(afv);
        ex.setVisible(true);

    }//GEN-LAST:event_grafikasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
        int kelintas = jTable1.getSelectedRow();
        PiniguJudejimas pasirinkta = afv.gautiJudejimus().get(kelintas);
        afv.salintiJudejima(pasirinkta.getNr());
        atnaujintiSarasa();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Pirma pasirinkite judejima, kuri norite istrinti");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    private void atnaujintiSarasa() {
        ArrayList<Kategorija> sar = afv.gautikategorijuSarasa();
        ArrayList<PiniguJudejimas> dydis = afv.gautiJudejimus();
        String[][] mas = new String[dydis.size()][6];
        DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
        int i = 0;

        //for (Kategorija k : sar) {
        //  ArrayList<PiniguJudejimas> sar2 = k.getJudejimas();
        for (PiniguJudejimas p : dydis) {
            mas[i][0] = p.getNr();
            mas[i][1] = p.gautiKategorijosPavadinima();
            mas[i][2] = p.getAprasymas();
            mas[i][3] = df.format(p.getData());
            mas[i][4] = Double.toString(p.getSuma());
            mas[i][5] = p.getTipas();

            i++;
        }
        //}

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                mas,
                new String[]{
                    "Nr","Kategorija", "Pavadinimas", "Data", "Suma", "tipas"
                }
        ));
    }

    private void filtruotiSarasa() {
        Date data1 = new Date();
        Date data2 = new Date();
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String datai1 = this.l_data1.getText();
        String datai2 = this.l_data2.getText();
        try {
            data1 = simpleDateFormat.parse(datai1);
            data2 = simpleDateFormat.parse(datai2);
            ArrayList<Kategorija> sar = afv.gautikategorijuSarasa();
            ArrayList<PiniguJudejimas> dydis = afv.gautiJudejimus();
            String[][] mas = new String[dydis.size()][6];
            DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            int i = 0;
            for (PiniguJudejimas p : dydis) {
                if ((data1.before(p.getData()) || data1.equals(p.getData())) && (data2.after(p.getData()) || data2.equals(p.getData()))) {
                    mas[i][0] = p.getNr();
                    mas[i][1] = p.gautiKategorijosPavadinima();
                    mas[i][2] = p.getAprasymas();
                    mas[i][3] = df.format(p.getData());
                    mas[i][4] = Double.toString(p.getSuma());
                    mas[i][5] = p.getTipas();
                    i++;
                }
            }

            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                    mas,
                    new String[]{
                        "Nr","Kategorija", "Pavadinimas", "Data", "Suma", "tipas"
                    }
            ));
            JOptionPane.showMessageDialog(this, "Sekmingai sufiltruota");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Prastai ivestos datos");
        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem KategorijosKurimas;
    private javax.swing.JMenuItem grafikas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField l_data1;
    private javax.swing.JTextField l_data2;
    private javax.swing.JButton m_filtruoti;
    // End of variables declaration//GEN-END:variables
}
