/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package antraslaboratorinis;

import DuomenuStrukturos.AsmeniniuFinansuValdymas;
import DuomenuStrukturos.Kategorija;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;

/**
 *
 * @author Berniszu
 */
public class IslaiduIvedimas extends javax.swing.JDialog {

    AsmeniniuFinansuValdymas a = null;

    /**
     * Creates new form IslaiduIvedimas
     */
    public IslaiduIvedimas(java.awt.Frame parent, boolean modal, AsmeniniuFinansuValdymas a) {
        super(parent, modal);
        this.a = a;
        initComponents();
        ArrayList<Kategorija> kat = a.gautikategorijuSarasa();
        String[] mas = new String[kat.size()];
        int i = 0;
        for (Kategorija k : kat) {
            mas[i] = k.getPavadinimas();
            i++;
        }
        l_kategorija.setModel(new javax.swing.DefaultComboBoxModel<>(mas));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        l_kategorija = new javax.swing.JComboBox<>();
        l_pavadinimas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        l_komentaras = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        l_nr = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        l_suma = new javax.swing.JTextField();
        l_data = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Kategorija:");

        jLabel2.setText("Pavadinimas:");

        jLabel3.setText("Data:");

        jLabel4.setText("Komentaras:");

        l_kategorija.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        l_kategorija.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_kategorijaActionPerformed(evt);
            }
        });

        l_pavadinimas.setText("Pavadinimas");
        l_pavadinimas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_pavadinimasActionPerformed(evt);
            }
        });

        l_komentaras.setColumns(20);
        l_komentaras.setRows(5);
        jScrollPane1.setViewportView(l_komentaras);

        jButton1.setText("Prideti");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Cekio nr:");

        l_nr.setText("XXX");
        l_nr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_nrActionPerformed(evt);
            }
        });

        jLabel6.setText("Suma:");

        l_suma.setText("0");
        l_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_sumaActionPerformed(evt);
            }
        });

        l_data.setText("2019-01-01");
        l_data.setToolTipText("yyyy-MM-dd");
        l_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_dataActionPerformed(evt);
            }
        });

        jLabel7.setText("Islaidos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel4)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_kategorija, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(l_pavadinimas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                            .addComponent(l_nr)
                            .addComponent(l_suma)
                            .addComponent(l_data)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(175, 175, 175))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(l_kategorija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(l_pavadinimas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(l_data, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(l_nr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_suma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void l_pavadinimasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_pavadinimasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_pavadinimasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Date data = new Date();
        data = GautiData(data);
        //System.out.println(data);
        boolean patikr = arTinkaData();
        String pav = this.l_pavadinimas.getText();
        String nr = this.l_nr.getText();
        String kat = l_kategorija.getSelectedItem().toString();
        double suma = Double.parseDouble(this.l_suma.getText());
        String kom = this.l_komentaras.getText();
        boolean pavyko;
        if (patikr == true) {
            pavyko = a.pridetiIslaida(suma, data, pav, kat, nr);
        } else {
            pavyko = false;
        }
        if (pavyko) {
            JOptionPane.showMessageDialog(this, "Islaida sekmingai prideta");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Ivesta bloga data arba toks numeris jau egzistuoja");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void l_kategorijaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_kategorijaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_kategorijaActionPerformed

    private void l_nrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_nrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_nrActionPerformed

    private void l_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_sumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_sumaActionPerformed

    private void l_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_dataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_dataActionPerformed
    public Date GautiData(Date date) {
        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String datai = this.l_data.getText();
        simpleDateFormat.setLenient(false);
        try {
            return date = simpleDateFormat.parse(datai);
            //System.out.println(date);

        } catch (Exception e) {
            System.out.println("Blogai ivesta data");
            return null;
        }
    }

    public boolean arTinkaData() {
        String dateToValidate = this.l_data.getText();
        if (dateToValidate == null) {
            return false;
        }
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        sdf.setLenient(false);
        try {
            Date date = sdf.parse(dateToValidate);
            //System.out.println(date);

        } catch (ParseException e) {

            return false;
        }
        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField l_data;
    private javax.swing.JComboBox<String> l_kategorija;
    private javax.swing.JTextArea l_komentaras;
    private javax.swing.JTextField l_nr;
    private javax.swing.JTextField l_pavadinimas;
    private javax.swing.JTextField l_suma;
    // End of variables declaration//GEN-END:variables
}
