/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package antraslaboratorinis;

import DuomenuStrukturos.AsmeniniuFinansuValdymas;
import DuomenuStrukturos.Kategorija;
import java.util.ArrayList;

/**
 *
 * @author Berniszu
 */
public class KategorijuSarasas extends javax.swing.JFrame {
    AsmeniniuFinansuValdymas a =null;
    /**
     * Creates new form KategorijuSarasas
     */
    public KategorijuSarasas(AsmeniniuFinansuValdymas b) {
        a = b;
        initComponents();
        atnaujintiKategorijuLentele();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        l_naujas_pav = new javax.swing.JTextField();
        l_naujas_apr = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setTitle("Kategorijos");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"A", "AA"},
                {"B", "BB"}
            },
            new String [] {
                "Pavadinimas", "Aprasymas"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Salint pasirinkta kategorijai");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        l_naujas_pav.setText("Naujas pavadinimas");

        l_naujas_apr.setText("Naujas aprasymas");
        l_naujas_apr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_naujas_aprActionPerformed(evt);
            }
        });

        jButton2.setText("Keisti pazymeta kategorija");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 643, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(30, 30, 30)
                .addComponent(l_naujas_pav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(l_naujas_apr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(l_naujas_pav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_naujas_apr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int kelintas = jTable1.getSelectedRow();
        Kategorija pasirinkta = a.gautikategorijuSarasa().get(kelintas);
        a.salintiKategorija(pasirinkta.getPavadinimas());
        atnaujintiKategorijuLentele();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void l_naujas_aprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_naujas_aprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_naujas_aprActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int kelintas = jTable1.getSelectedRow();
        Kategorija pasirinkta = a.gautikategorijuSarasa().get(kelintas);
        a.keistiKategorijosPavadinima(pasirinkta.getPavadinimas(),l_naujas_pav.getText());
        atnaujintiKategorijuLentele();
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void atnaujintiKategorijuLentele(){
         ArrayList<Kategorija> sar = a.gautikategorijuSarasa();
         String[][] mas = new String[sar.size()][2];
         int i=0;
         for(Kategorija k:sar){
             mas[i][0] = k.getPavadinimas();
             mas[i][1] = k.getAprasymas();
             i++;
         }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            mas,
            new String [] {
                "Pavadinimas", "Aprasymas"
            }
        ));
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField l_naujas_apr;
    private javax.swing.JTextField l_naujas_pav;
    // End of variables declaration//GEN-END:variables
}
